package com.encrypted.chat.swing;

import javax.swing.DefaultListModel;

import com.encrypted.chat.models.MissatgeDesencriptat;
import com.encrypted.chat.models.Persona;
import com.encrypted.chat.models.MissatgeDesencriptat.TipusMissatgeDesencriptat;
import com.encrypted.chat.tcp.ReceptorTCP;
import com.encrypted.chat.udp.ReceptorUDP;
import com.encrypted.chat.udp.RemitentUDP;
import com.encrypted.chat.udp.UtilsUDP;
import com.encrypted.chat.utils.Core;
import com.encrypted.chat.utils.UI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ivan
 */
public class ChatWindow extends javax.swing.JFrame implements UI{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ChatWindow.class.getName());
    
    private Core core;

    private ReceptorTCP receptorTCP;
    private RemitentUDP remitentUDP = new RemitentUDP();
    private ReceptorUDP receptorUDP;

    private Persona persona;

    private DefaultListModel<Persona> modelUsuaris;
    public ChatWindow() {
        initComponents();
    }
    /**
     * Creates new form ChatWindow
     */
    public ChatWindow(Persona persona) {
        this.persona = persona;
        initComponents();
        setVisible(true);

        core = new Core(this);
        receptorUDP = new ReceptorUDP(core, persona);
        receptorTCP = new ReceptorTCP(core, persona);

        Thread receptorTCPFil = new Thread(receptorTCP);
        Thread receptorUDPFil = new Thread(receptorUDP);
        Thread utils = new Thread(new UtilsUDP(persona));
        receptorTCPFil.start();
        receptorUDPFil.start();
        utils.start();

        mostrarMissatge(new MissatgeDesencriptat(TipusMissatgeDesencriptat.CONNECTAT, persona, "Client " + persona.getNom() + " connectat."));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtScrollChat = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        txtMsg = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        txtLlistaUsuaris = new javax.swing.JScrollPane();
        listUsuaris = new javax.swing.JList<>();
        lblLlista = new javax.swing.JLabel();
        lblChat = new javax.swing.JLabel();
        btnSeleccionarUsuari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        txtScrollChat.setName("textChat"); // NOI18N

        txtChat.setColumns(20);
        txtChat.setRows(5);
        txtScrollChat.setViewportView(txtChat);

        txtMsg.setToolTipText("");
        txtMsg.setActionCommand("<Not Set>");
        txtMsg.setName("textMsg"); // NOI18N
        txtMsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsgActionPerformed(evt);
            }
        });

        btnEnviar.setBackground(new java.awt.Color(204, 255, 204));
        btnEnviar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEnviar.setText("Enviar");
        btnEnviar.setName("btEnviar"); // NOI18N

        modelUsuaris = new DefaultListModel<>();
        listUsuaris.setModel(modelUsuaris);

        txtLlistaUsuaris.setViewportView(listUsuaris);

        lblLlista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLlista.setText("Llista d'usuaris disponibles");
        lblLlista.setName("Llista d'usuaris"); // NOI18N

        lblChat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblChat.setText("Xat");
        lblChat.setName("Llista d'usuaris"); // NOI18N

        btnSeleccionarUsuari.setBackground(new java.awt.Color(205, 205, 251));
        btnSeleccionarUsuari.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSeleccionarUsuari.setText("Seleccionar usuari(s)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLlistaUsuaris)
                            .addComponent(btnSeleccionarUsuari, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblLlista)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMsg)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEnviar))
                            .addComponent(txtScrollChat, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lblChat, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLlista)
                    .addComponent(lblChat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtScrollChat, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtLlistaUsuaris, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(btnSeleccionarUsuari)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMsg)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        btnEnviar.addActionListener(e -> System.out.println("Button was clicked!"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsgActionPerformed
    }//GEN-LAST:event_txtMsgActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ChatWindow().setVisible(true));
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnSeleccionarUsuari;
    private javax.swing.JLabel lblChat;
    private javax.swing.JLabel lblLlista;
    private javax.swing.JList<Persona> listUsuaris;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JScrollPane txtLlistaUsuaris;
    private javax.swing.JTextField txtMsg;
    private javax.swing.JScrollPane txtScrollChat;
    // End of variables declaration//GEN-END:variables

    @Override
    public void mostrarMissatge(MissatgeDesencriptat missatge) {
        switch (missatge.getTipus()) {
            case CONNECTAT:
                txtChat.append(missatge.getMissatge());
                break;
            case NOU_CLIENT:
                modelUsuaris.addElement(missatge.getEmisor());
                break;
            case TREURE_CLIENT:
                modelUsuaris.removeElement(missatge.getEmisor());
                break;
            case MISSATGE:
                txtChat.append(missatge.getEmisor() + ": " + missatge.getMissatge());
                break;
        
            default:
                break;
        }

        
    }
}
